Check if use_inline_resources is defined before using
use_inline_resources is not defined in all versions of Chef, yielding:
"NameError: undefined local variable or method `use_inline_resources' ..."